---
- hosts: servidores
  remote_user: ansible
  become: yes
  become_method: sudo
  
  roles:
  - role: './roles/apache-centos'
  #- when: ansible_facts['distribution'] == "CentOS"
    when: ansible_facts['os_family'] == "RedHat"
  
  tasks:

  - name: Create virtualhost content directories
    file:
      path: "{{ item }}"
      recurse: yes
      state: directory
      owner: apache
      group: apache
      mode: '0755'
    loop:
      - /var/www/{{ sitio }}
      - /var/www/{{ sitio }}/html
      - /var/www/{{ sitio }}/cgi-bin

  - name: Create virtualhost configuration
    template: 
      src: templates/{{ sitio }}.j2
      dest: /etc/httpd/vhost.d/{{ sitio }}.conf
      owner: root
      mode: '0644'
    notify: Restart httpd

  handlers:
  - name: Restart httpd
    service:
      name: httpd
      state: restarted
      enabled: yes
