---
- hosts: servidores
  remote_user: ansible
  become: yes
  become_method: sudo
  vars:
    sitio: ejemplo
    server: www.ejemplo.com.uy
    hostmaster: admin@ejemplo.com.uy
    
  roles:
  - role: './roles/apache-centos'
  #- when: ansible_facts['distribution'] == "CentOS"
    when: ansible_facts['os_family'] == "RedHat"
  
  tasks:

  - name: Create virtualhost content directories
    file:
      path: "{{ item }}"
      recurse: yes
      state: directory
      owner: ansible
      group: ansible
      mode: '0755'
    loop:
      - /var/www/{{ sitio }}
      - /var/www/{{ sitio }}/html
      - /var/www/{{ sitio }}/cgi-bin
   
   -name: Create loadbalancer configuration
    template:
      scr: template/loadbalancer.j2
      dest: /etc/httpd/vhost.d/loadbalancer.conf
      owner: root
      mode: '0644'
    when: ansible_fact['os_family'] == "Redhat"
    notify: Restart httpd

  handlers:
  - name: Restart httpd
    service:
      name: httpd
      state: restarted
      enabled: yes
